src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Duration_Seconds__c</fullName>
        <label>Duration Seconds</label>
        <summarizedField>Song__c.Duration_Seconds__c</summarizedField>
        <summaryForeignKey>Song__c.Album__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>TEXT(FLOOR( Duration_Seconds__c /60))&amp;&quot;:&quot;&amp; TEXT(MOD( Duration_Seconds__c ,60))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Songs</relationshipLabel>
        <relationshipName>Songs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration_Seconds__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Duration Seconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>&quot;00:00&quot;</defaultValue>
        <label>Duration</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Number__c</fullName>
        <label>Track Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestConvertDurationToSeconds.cls
@isTest
private class TestConvertDurationToSeconds {
    static void init(){}
   	static testMethod void testTimeConversion(){
        Album__c testAlbum = new Album__c(Name='Test Album');
        insert testAlbum;
		Song__c song = new Song__c(
        	Name='Test Song 1',
            Duration__c='1:20',
            Album__c=testAlbum.Id,
            Track_Number__c=1
        );
        insert song;
        Song__c testSong = [Select Duration_Seconds__c from Song__c where Id=:song.Id limit 1];        
        System.assertNotEquals(testSong.Id, null);
        System.assertEquals(80, testSong.Duration_Seconds__c);

    }
}