src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Spotify_URI__c</fullName>
        <label>Spotify URI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Songs</relationshipLabel>
        <relationshipName>Songs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Spotify_URI__c</fullName>
        <label>Spotify URI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SpotifyWebService.cls
global class SpotifyWebService {
    webservice static Boolean importTrackListing(String albumId){
     	Album__c album = SpotifyWebService.findAlbum(albumId);
        List<Song__c> songs = SpotifyHelper.getTrackListing(album);
		insert songs;
        return true;
    }
    
    public static Album__c findAlbum(String albumId){
        return [Select a.Name, a.Spotify_URI__c From Album__c a WHERE a.Id=:albumId LIMIT 1];
    }
}