src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>TEXT(FLOOR( Duration_Seconds__c /60))&amp;&quot;:&quot;&amp; TEXT(MOD( Duration_Seconds__c ,60))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spotify_URI__c</fullName>
        <label>Spotify URI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Songs</relationshipLabel>
        <relationshipName>Songs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>&quot;00:00&quot;</defaultValue>
        <label>Duration</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spotify_URI__c</fullName>
        <label>Spotify URI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Number__c</fullName>
        <label>Track Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SpotifyHelper.cls
public class SpotifyHelper {
   public static List<Song__c> getTrackListing(Album__c album){
        //adding a comment here to test if the deply worked
        String albumId = SpotifyHelper.stripURI(album.Spotify_URI__c);
		HttpRequest req = SpotifyHelper.createTracksRequest(albumId);
        Http sender = new Http();
        HTTPResponse res = sender.send(req);
		Map<String, Object> resParsed = SpotifyHelper.unpackResponse(res.getBody());
		Object[] tracks = (Object[])resParsed.get('items');
        List<Song__c> songs = new List<Song__c>();
        for(Object t : tracks){
			Map<String, Object> m = (Map<String, Object>)t;
            String duration = SpotifyHelper.convertToTimecode((Integer)m.get('duration_ms'));
			songs.add(new Song__c(
                Name=(String)m.get('name'),
                Track_Number__c=(Integer)m.get('track_number'),
                Duration__c=duration,
                Album__c=album.Id,
                Spotify_URI__c = (String)m.get('uri')
            ));
        }		
		return songs;
    }
    
    private static HttpRequest createTracksRequest(String alId){
        String requestUrl = 'https://api.spotify.com/v1/albums/' + alId + '/tracks';
        return SpotifyHelper.createRequestFromUrl(requestUrl);
        
    }
    
    private static HttpRequest createAlbumRequest(String alId){
		String requestUrl = 'https://api.spotify.com/v1/albums/' + alId;
        return SpotifyHelper.createRequestFromUrl(requestUrl);
    }
    
    private static HttpRequest createRequestFromUrl(String url){
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('GET');
        return req;
    }
    
    private static Map<String, Object> unpackResponse(String res){
        return (Map<String, Object>)JSON.deserializeUntyped(res);
    }
    
    public static String convertToTimecode(Integer dur){
        Integer sec = dur/1000;
        Integer min = sec/60;
        Integer seco = Math.mod(sec, 60);
        String minStr = (min < 10 ? '0' : '') + String.valueOf(min);
        String seconds = (seco < 10 ? '0' : '') + String.valueOf(seco);
        return min + ':' + seconds;
    }
    
    /**
     * returns the id of the object requested
     */
    private static String stripURI(String uri){
        List<String> pieces = uri.split(':');
        return pieces.get(pieces.size() - 1);
    }
}