src/objects/Album__c.object
<CustomObject>
    <fields>
        <fullName>Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Artist</label>
        <referenceTo>Artist__c</referenceTo>
        <relationshipLabel>Albums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>TEXT(FLOOR( Duration_Seconds__c /60))&amp;&quot;:&quot;&amp; TEXT(MOD( Duration_Seconds__c ,60))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Photo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Photo</label>
        <referenceTo>skuid__Image__c</referenceTo>
        <relationshipLabel>Albums (Photo)</relationshipLabel>
        <relationshipName>Albums1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Artist__c.object
<CustomObject>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Genre__c.object
<CustomObject>
    <label>Genre</label>
    <nameField>
        <label>Genre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GenreAlbum__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>GenreAlbums</relationshipLabel>
        <relationshipName>Genres</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <referenceTo>Genre__c</referenceTo>
        <relationshipLabel>GenreAlbums</relationshipLabel>
        <relationshipName>Albums</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GenreAlbum</label>
    <nameField>
        <displayFormat>GA-{0}</displayFormat>
        <label>GenreAlbum Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GenreAlbums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/skuid__Image__c.object
<CustomObject>
    <fields>
        <fullName>skuid__Url__c</fullName>
        <description>Url for viewing/downloading this File.</description>
        <formula>&apos;/servlet/servlet.FileDownload?file=&apos; &amp; skuid__AttachmentId__c</formula>
        <label>Url</label>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <label>File Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Album__c</fullName>
        <label>Album</label>
        <referenceTo>Album__c</referenceTo>
        <relationshipLabel>Songs</relationshipLabel>
        <relationshipName>Songs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <defaultValue>&quot;00:00&quot;</defaultValue>
        <label>Duration</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Number__c</fullName>
        <label>Track Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LightningAlbumController.cls
public class LightningAlbumController {
	@AuraEnabled
    public static List<Album__c> getAlbums(Id genreId){
        if(genreId == null){
            return [Select Id, Name, Duration__c, Artist__r.Name From Album__c];    
        }
        
        Genre__c genre = [Select Id from Genre__c Where Id = :genreId limit 1];
        return [Select Id, Name, Duration__c, Artist__r.Name 
        From Album__c 
        Where (Id In (
            Select Album__c from GenreAlbum__c WHERE Genre__c = :genre.Id))
        ];
        
    }

    @AuraEnabled
    public static Album__c getAlbumFromId(Id albumId){

    	Album__c album = 
    		[ SELECT Id, Name, Duration__c, Artist__r.Name, Photo__r.skuid__Url__c From Album__c  Where Id = :albumId Limit 1];

    	return album;
    }
    @AuraEnabled
    public static Song__c[] getSongsForAlbum(Id albumId){
    	Song__c[] songs = [Select Name, Duration__c, Track_Number__c From Song__c Where Album__r.Id = :albumId Order By Track_Number__c ASC];
    	return songs;
    }

    @AuraEnabled
    public static Song__c deleteSong(Song__c song){
    	delete song;
    	return song;
    }

    @AuraEnabled
    public static Song__c createSong(Song__c song){
    	insert song;
    	return song;
    }

}